# Site settings
title: Aspiranet 
email: nicolas@aspiranet.org
description: >
  Aspiranet envisions a world in which all children and
  youth are loved and cared for and all families have the
  resources to thrive.
baseurl: ""
url: "https://www.aspiranet.org" # the base hostname & protocol for your site
image_path: '/assets/img'

# Build settings
markdown: kramdown
permalink: pretty
exclude: ['_sass', '_src', '_grunt', 'node_modules', 'Gruntfile.js', 'package.json', 'README.md', 'Gemfile']

gems: ['jekyll-twitter-plugin']