# Site settings
title: Aspiranet 
email: nicolas@aspiranet.org
description: >
  Aspiranet envisions a world in which all children and
  youth are loved and cared for and all families have the
  resources to thrive.
baseurl: ""
url: "https://www.aspiranet.org" # the base hostname & protocol for your site
image_path: '/assets/img'

# Build settings
markdown: kramdown
permalink: pretty
exclude: ['_sass', '_src', '_grunt', 'node_modules', 'Gruntfile.js', 'package.json', 'README.md', 'Gemfile']

gems: [ 
"jekyll-twitter-plugin", 
"jekyll-contentful"
]

contentful:
  preview: Yes 
  production_access_token: 207be5e580e324a1e1208a4c4ace90ad46a95f27d35b14bae5ab042497155885 #Access
  preview_access_token: 75dd77ee4c831dd26fbde7d5f39287c2cd26ac4ceff0dec1f31f503a2d9dfdec #Preview
  space: e5ehlcazegi0
  content_types:
   - "blogPost"
   - "campain"
   - "divisionHeads"
   - "programs"
   - "seniorExecutive"
  spaces:
    - proddata:
        space: e5ehlcazegi0
        access_token: 75dd77ee4c831dd26fbde7d5f39287c2cd26ac4ceff0dec1f31f503a2d9dfdec #Spaces
        cda_query:
          include: 2
          limit: 100
        content_types:
          cat: blogPost
          cat: campain
          cat: divisionHeads
          cat: programs
          cat: seniorExecutive
          cat: rootWebsite
        client_options:
          api_url: 'preview.contentful.com'

