# Site settings
title: Aspiranet 
email: nicolas@aspiranet.org
description: >
  Aspiranet envisions a world in which all children and
  youth are loved and cared for and all families have the
  resources to thrive.
baseurl: ""
url: "https://www.aspiranet.org" # the base hostname & protocol for your site
image_path: '/assets/img'

# Build settings
markdown: kramdown
permalink: pretty
exclude: ['_sass', '_src', '_grunt', 'node_modules', 'Gruntfile.js', 'package.json', 'README.md', 'Gemfile']

gems: [ 
"jekyll-twitter-plugin", 
##"jekyll-contentful"
]

contentful:
  preview: ASPIRANET_CONTENTFUL_IS_PREVIEW 
  production_access_token: ASPIRANET_CONTENTFUL_ACCESS_KEY
  preview_access_token: ASPIRANET_CONTENTFUL_PREVIEW_KEY
  space: ASPIRANET_CONTENTFUL_SPACE_ID
  content_types:
   - "blogPost"
   - "campain"
   - "divisionHeads"
   - "programs"
   - "seniorExecutive"
  spaces:
    - proddata: # Jekyll _data folder identifier - Required
        space: ASPIRANET_CONTENTFUL_SPACE_ID        # Required
        access_token: ASPIRANET_CONTENTFUL_ACCESS_KEY # Required
        cda_query:
          include: 2
          limit: 100
        content_types:
          cat: blogPost
          cat: campain
          cat: divisionHeads
          cat: programs
          cat: seniorExecutive
          cat: rootWebsite
        client_options:
          api_url: ASPIRANET_CONTENTFUL_API_URL
